### ISSUE TITLE
open last project

### ISSUE THREAD

**Issue by basz** [jcbvm/i18n-editor#13]
an 'open last project' setting would be very much appreciated. Or perhaps the file browser can remember where is was on the disk.

thanks for e very useful tool

**Comment by jcbvm** [comment]
This should already be the case. If you close the editor, it stores the current project path and selected nodes in a configuration file `.i18n-editor` in your user directory. The next time you open the editor, it should open the previously store project and expand the last open nodes.

If this is not the case for you, let me know to see if there's a bug somewhere.

**Comment by basz** [comment]
Hi, it does not. Am using the beta version on mac.

**Comment by jcbvm** [comment]
Thanks for reporting, will take a look at it 👍

**Comment by jcbvm** [comment]
This should now be fixed in 1.0.0-beta.2
