### ISSUE TITLE
beta2 (osx) non functional menu

### ISSUE THREAD

**Issue by basz** [jcbvm/i18n-editor#14]
Last update now did not fix 'open recent' issue. Instead the whole 'file' menu is not inaccessible. So you can't save at all

https://www.dropbox.com/s/4dg1jky5pbe5ytd/Screen%20Shot%202017-02-06%20at%2013.29.42.png?dl=0

**Comment by jcbvm** [comment]
I'm aware of this issue, will take a look at it soon.

**Comment by jcbvm** [comment]
Fix available in beta 3
