### ISSUE TITLE
Add keyboard navigation

### ISSUE THREAD

**Issue by jcbvm** [jcbvm/i18n-editor#19]
The tree should be navigatable via arrow keys at any time (with for example the alt meta key). Focus should remain where it is, unless a translation field is focused and no leaf node is currently selected. In the latter case focus should return to the first translation field when a leaf node is selected again.

See #15

**Comment by jensmtg** [comment]
I was looking for this functionality, but it took me some time to figure out the hotkeys (alt-meta) to do this. Maybe add a line or two to the documentation?

**Comment by Luxor001** [comment]
It doesn't seems to work for me: if i understand the committed code correctly, i need to press left ALT and then press arrow keys to navigate in the keys trees?

I am using the .exe version of 2.0.0-beta-1
