### ISSUE TITLE
Adding Key to already existing one.

### ISSUE THREAD

**Issue by Dicsolovag** [jcbvm/i18n-editor#24]
Hi!

I found a strange behaviour. When I add a key to an existing parent node, its all good. I got a leaf node and  its all good.
But! If I add a node to an already existing leaf node (which has translation values) that already existing value is removed, when that node is converted into a parent node.
At least a notification about that value erasure would be great, or the possibility to move the value a level down, with the same key name.
This can be achieved by rename key function, because in that case I can insert a key anywhere in that path.
But, this behaviour would be great during simple addition, if I insert key under a leaf key.

Thanks 
Tom

**Comment by jcbvm** [comment]
Thanks for your feedback and you are right, currently a leaf node will be overridden when adding nodes to it. Will take your suggestion in consideration 👍
