### ISSUE TITLE
Font Size Adjustments Setting

### ISSUE THREAD

**Issue by tvoloshyn** [jcbvm/i18n-editor#26]
Dear Jacob,

Thank you for such a wonderful tool ! One thing which I think would be useful to have is the ability to change font size within inputs. I've used your tool to translate a pretty big project and I found it to be hard to concentrate on the inputs for a long time, as the font at the moment is relatively small.

Thanks,
T

**Comment by jcbvm** [comment]
Can you share a screenshot? The font size depends on the operating system. I know there are some troubles with high resolutions, because of the lack of support for it in java. So I'm wondering which operating system you are using and which resolution your screen is.

**Comment by jcbvm** [comment]
Closing this issue for now
