### ISSUE TITLE
Double Click — Smarter Selection Behaviour

### ISSUE THREAD

**Issue by tvoloshyn** [jcbvm/i18n-editor#27]
Hi Jacob,

Thanks for the great tool. I've been translating a lot with your tool recently and one of the features I think would be useful is to change the default behavior of double click selection, when editing/creating new translation key.

At the moment when you double click, entire input field is selected. It would be good to only select the part of text before/after the dot. So in case of "website.main.title" key, if I double click in the area of "website", only "website" is selected, if inside "main", then only "main", etc.

This would speed up the translation process when it comes to renaming, duplication, copy/pasting from code editors, etc.

Thanks,
T

**Comment by jcbvm** [comment]
Great improvement indeed. Will mark this issue as an improvement.
