### ISSUE TITLE
Translations File by Language Name

### ISSUE THREAD

**Issue by alexvcasillas** [jcbvm/i18n-editor#28]
Hello, I'm opening this issue because I would like to know if it's possible to generate the `translations.json` file based on the `translation key` provided.

For example:
If I've created a translation key called `es_es` I would like to have the `translations.json` file with the same name as the key, in this case `es_es.json`.

This thing will be a huge benefit based on my needs due to the fact that I need it to be this way and we need like 8 different language resources and the translations team needs to work seamlessly with the development team to make things just, edit, upload and go.

Warm, regards!
Thanks!

**Comment by jcbvm** [comment]
Currently this is not possible, for this I would have to add an option to format the way the files are saved.
I will mark this issue as a new feature.

**Comment by alexvcasillas** [comment]
Awesome, thanks for the answer, we'll be in touch! ;)

**Comment by t-p-l-k** [comment]
Would like to see this implemented too!
Thanks in advance.

**Comment by elupanov** [comment]
It would be a very useful feature

**Comment by Chuvisco88** [comment]
+1

**Comment by JohnChantzis** [comment]
+1

**Comment by jcbvm** [comment]
Will be part of 2.0.0

**Comment by tinmar33** [comment]
Any update for it ?
