### ISSUE TITLE
Value parent key cannot be changed

### ISSUE THREAD

**Issue by HaaiHenkie** [jcbvm/i18n-editor#29]
Hello Jacob,

I am evaluating some tools for translation of java property files. I have the following keys in my translations properties file:
```
addons.gtdSyncWithTodoTxt=GTD Sync with todo.txt
addons.gtdSyncWithTodoTxt.gtdSync=GTD Sync
addons.gtdSyncWithTodoTxt.Project=Project
addons.gtdSyncWithTodoTxt.NextAction=Next action
addons.gtdSyncWithTodoTxt.CompletedAction=Completed
addons.gtdSyncWithTodoTxt.GTDSyncQuickStart=GTD Sync Help: quick start
addons.gtdSyncWithTodoTxt.ConvertLanguage=Convert GTD mind map to English
addons.gtdSyncWithTodoTxt.Archive=Archive
```
I am not able to change the first key, which is the parent key of the other keys. I can do it with the other tools that I have tried (java properties editor <http://www.mightyfrog.org/softwares/i18n/i18n.html> and Eclipse ResourceBundle Editor <http://essiembre.github.io/eclipse-rbe/>). I see this as a bug and it is obviously related to feature request #24.

**Comment by jcbvm** [comment]
Thx for reporting. 
You are right indeed, at the moment it's not possible to assign a value to a parent key (personally I would never assign a value to a parent key, because it makes the conversion to JSON or XML impossible).

**Comment by HaaiHenkie** [comment]
Hello Jacob,

I am developing and translating a Freeplane add-on. The above translation keys are standard for Freeplane add-ons: the parent key carries the add-on name, the other keys are naming the scripts and their menu items. I actually do not use any other parent key for translation. I also do not need conversion to JSON or XML.

Cheers,

Henk
