### ISSUE TITLE
Save translations in en.json / de.json format

### ISSUE THREAD

**Issue by JavanXD** [jcbvm/i18n-editor#31]
I am using [ngx-translate](https://github.com/ngx-translate/core) in my Angular2+ App and your i18n-editor looks great but is not conform with the filenameing standards in my Angular App.
The opportunity to change the naming to the selected language would be great.

![grafik](https://user-images.githubusercontent.com/4342160/30061762-f8a675b8-9248-11e7-8593-5a3d3d882a17.png)

**Comment by JavanXD** [comment]
## Workaround in Angular:
```
export function createTranslateLoader(http: HttpClient) {
	return new TranslateHttpLoader(http, './assets/i18n/', '/values.json');
}
```
After setting my TranslateLoader in my Angular App to this path it worked but there should be a GUI Option in this i18n-editor to change the folder structure.

**Comment by jcbvm** [comment]
This will be coming in the next release.

**Comment by ndrake** [comment]
Any ideas on when the next release will be ready?

**Comment by hadikcz** [comment]
So, when will be next release ?

**Comment by jcbvm** [comment]
Next release is coming this week

**Comment by jcbvm** [comment]
Duplicate of #28
