### ISSUE TITLE
Editing JSON file

### ISSUE THREAD

**Issue by reinierkors** [jcbvm/i18n-editor#35]
Hi,

I'm trying to edit the following JSON file:
```
{
  "Aantal": "Amount",
  "Betaalmethode": "Payment method",
  "Contact": "Contact us"
}
```

But I can't seem to import it.

**Comment by jcbvm** [comment]
The app follows a strict project structure. You can't simple edit json files on demand. 
See the docs for what structure is required or simply create a new project to see the structure being used.

In the upcoming release (2.0.0) the project structure will be simplified.
