### ISSUE TITLE
Specify translation files

### ISSUE THREAD

**Issue by eduardolima93** [jcbvm/i18n-editor#38]
Hi,

First of, very nice editor!

Would it be possible to specify the translation jsons instead having to follow the project folder structure? I have an existing project where the i18n jsons are inside the same folder, therefore the editor doesn't find them.

Bests,

**Comment by jcbvm** [comment]
This will be part of release 2.0.0 coming soon!

**Comment by jcbvm** [comment]
Duplicate of #28
