### ISSUE TITLE
JSON Translations, key options

### ISSUE THREAD

**Issue by vickyvxr** [jcbvm/i18n-editor#41]
Would it be possible to add a new options when creating JSON translations files, to change the output file from:
{
  "login": {
    "login": "Entrar   sssdds",
    "password": "Contraseña",
    "username": "Nombre de usuario"
  }
}

To:
{
  "login.login": "Entrar",
  "login.username": "Nombre de usuario",
  "login.password": "Contraseña"
}

It will be great to use this tool with react-intl library.

Thanks!!!

**Comment by kopach** [comment]
I can't wait to have this feature released. I do also need to have flat json keys instead of nested ones for my project.

**Comment by vickyvxr** [comment]
I finally implemented it by myself.
I did a Pull request to this repository: https://github.com/jcbvm/i18n-editor/pull/42

Feel free to test it and give me your feed back!

**Comment by kopach** [comment]
Yes, it seems to work as expected. I'll test it a little bit more and give you my response later

**Comment by kopach** [comment]
@vickyvxr , after some time of usage, the only thing I would change - it's naming.
Instead of `Plain JSON keys` I would name it as `Flat keys` or `Flat structure` (as opposite to nested structure we do currently have).

And, maybe, would be great to add this option application wide, not only per project.

**Comment by jcbvm** [comment]
Looks great, flat structure is the better name indeed. Will merge this into next release

**Comment by jcbvm** [comment]
@vickyvxr I will also add it to the global settings thanks!
