### ISSUE TITLE
Highlight the keys with missing locale values

### ISSUE THREAD

**Issue by arunprasadr** [jcbvm/i18n-editor#5]
It would be very helpful if the keys with missing locale values were highlighted in red color or with some sort of small warning icons before the key.

**Comment by jcbvm** [comment]
Any keys without any value will by default be removed when saving, so this would only be helpful when importing empty key-values or adding keys without immediately setting a value.

**Comment by zloyreznic** [comment]
+1

**Comment by zloyreznic** [comment]
When will be done this future? Very necessary

**Comment by jcbvm** [comment]
This won't probably be implementated for the coming 1.0.0 anymore. So not sure yet when.

**Comment by zloyreznic** [comment]
:(

**Comment by zloyreznic** [comment]
This is main functionality... We lost more time to find untranslated words

**Comment by jcbvm** [comment]
The implementation of this is now part of 1.0.0-beta.4

**Comment by zloyreznic** [comment]
You are the best!!!

**Comment by jcbvm** [comment]
Fixed in upcoming 1.0.0 release
