### ISSUE TITLE
No 'flatten on save' option

### ISSUE THREAD

**Issue by alparius** [jcbvm/i18n-editor#70]
The readme says that it can be set to flatten the json on save, however this option doesn't seem to appear anywhere.

**Comment by rodmax** [comment]
it seems this feature presented in version `2.0.0-beta-1`
https://github.com/jcbvm/i18n-editor/releases/tag/2.0.0-beta.1

I not tested it yet just run application and found this

![image](https://user-images.githubusercontent.com/6079597/63625277-cee9a480-c607-11e9-8ff3-83c9478e80a1.png)

**Comment by alparius** [comment]
> it seems this feature presented in version `2.0.0-beta-1`
> https://github.com/jcbvm/i18n-editor/releases/tag/2.0.0-beta.1
> 
> I not tested it yet just run application and found this

It does indeed work, thank you!
